### ISSUE TITLE
Script Editor not present in Notifications & Focus pane

### ISSUE THREAD

**Issue by philgyford** [JackWellborn/Nightly-Time-Machine#2]
I was following the README, but at Step 6 ("Adjust notifications for Script Editor in the Notifications & Focus preference pane…") Script Editor isn't listed in the pane for me (screenshot below).

The app is there at `HD/Applications/Utilities/Script Editor.app`

I don't think I've used it on this Mac before but I opened it, and saved a script, in case that nudged it into appearing, but no joy.

Any suggestions? I'm on macOS 12.5, MacBook Pro (14-inch, 2021).

(Thanks so much for this!)

![Screenshot 2022-08-20 at 12 30 38](https://user-images.githubusercontent.com/66670/185744046-48fe3428-8e62-48b9-ac08-3d4dc316835c.png)

**Comment by JackWellborn** [comment]
My guess is that apps don't appear in this list until they try to send a notification. Could you try this command in the terminal: `osascript -e 'display notification "Hello World"`, and then see if Script Editor appears in the Notifications preferences?

**Comment by philgyford** [comment]
Sorry, this got lost in an inbox of GitHub notifications. Now I go back to Notification settings, Script Editor is there! Maybe you're right, and in that time it tried sending a notification and so it's now appeared.

Thank you for your help, and for this handy tool.

**Comment by faximan** [comment]
FWIW, I also don't have Script Editor in the list (latest Sequoia 15.2).

> osascript -e 'display notification "Hello World"'

This returned successfully but as far as I can tell nothing happened and I still don't see it in the list (also restarted System Settings).

<img width="548" alt="Screenshot 2024-12-28 at 11 22 42" src="https://github.com/user-attachments/assets/76287d7e-4f85-4a0d-b9e9-d111697a176d" />

**Comment by faximan** [comment]
I solved this by opening Script Editor.app and ran `display notification "Hello World"` in a new document. That made the "allow notifications?" banner to pop up.

Maybe this can be added to the README.
