### ISSUE TITLE
Suggestion: scripts could be double-clickable with .tool

### ISSUE THREAD

**Issue by chuckhoupt** [JackWellborn/Nightly-Time-Machine#5]
If the shell scripts use the extensions `.command` or `.tool` rather than `.sh`, then they can be double-clicked in the Finder to launch in Terminal.app. This can be convenient for users who aren't comfortable with the command line.

**Comment by JackWellborn** [comment]
Thanks for the tip!  I renamed the enable and disable scripts and updated the Read Me.

**Comment by chuckhoupt** [comment]
Great!
